#pragma config(Sensor, S4,     LightSensor,         sensorLightActive)
#pragma config(Motor,  motorB,          motorB,        tmotorNormal, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void set_steering_angle(int angle);

int steeringAngle = 45;

task main()
{
  set_steering_angle(0);
  wait1Msec(1500);
  set_steering_angle(90);
  wait1Msec(1500);
  set_steering_angle(45);
}

void set_steering_angle(int angle)
{
  int direction = 1;

  // base case
  if(angle == steeringAngle) return;

  // reverse direction if need be
  if(angle < steeringAngle) direction = -1;

	// reset motor encoder value and set motor speeds
	nMotorEncoder[motorB] = 0;
	motor[motorB] = 25 * direction;

	// wait for desired motor encoder value
	while( abs(nMotorEncoder[motorB]) != abs(angle-steeringAngle) );

	// stop motor and return
	motor[motorB] = 0;
	steeringAngle = angle;
	return;
}
