#pragma config(Sensor, S4,     LightSensor,         sensorLightActive)
#pragma config(Motor,  motorB,          steerMotor,    tmotorNormal, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
  int nLight;

	nSchedulePriority = kDefaultTaskPriority;
	//SensorMode[LightSensor] = modeRaw;
	while(true)
	{
	  // delay 3 milliseconds since that's the fastest the sensor can read
		wait1Msec(3);

		// take a reading
		nLight = SensorValue(LightSensor);
		nxtDisplayCenteredBigTextLine(4, "%d", nLight);

		//wait1Msec(500);
	}
}
